version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
    - whitespace
    - gocyclo
    - dupl
    - prealloc
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - copyloopvar
    - goconst
    - godot
    - errorlint
    - revive

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    - format: colored-line-number
      path: stdout
  sort-results: true
