version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
    - whitespace
    - gocyclo
    - dupl
    - prealloc
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
    - copyloopvar
    - goconst
    - godot
    - errorlint

formatters:
  enable:
    - gofmt
    - goimports
