version: 2

project_name: bab

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy
    - go mod download
    - ./scripts/completions.sh

builds:
  - id: default
    binary: bab
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/bab-sh/bab/internal/version.Version={{.Version}}
      - -X github.com/bab-sh/bab/internal/version.Commit={{.FullCommit}}
      - -X github.com/bab-sh/bab/internal/version.Date={{.Date}}
      - -X github.com/bab-sh/bab/internal/version.BuiltBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'

universal_binaries:
  - id: bab-universal
    ids:
      - default
    replace: false
    name_template: 'bab'

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "windows" }}Windows
      {{- else if eq .Os "darwin" }}macOS
      {{- else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  extra_files:
    - glob: ./LICENSE
    - glob: ./README.md

source:
  enabled: true

signs:
  - id: checksum-sign
    cmd: cosign
    certificate: "${artifact}.pem"
    artifacts: checksum
    output: true
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

release:
  github:
    owner: bab-sh
    name: bab
  mode: append

nfpms:
  - id: packages
    package_name: bab
    vendor: bab-sh
    homepage: https://github.com/bab-sh/bab
    maintainer: Sebastian Stepper <sebastian-stepper@gmx.de>
    description: A Simple Task Runner
    license: MIT

    formats:
      - deb
      - rpm
      - apk
      - archlinux

    bindir: /usr/bin

    dependencies: []
    recommends: []
    suggests: []

    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/bab/LICENSE
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/bab/README.md
        file_info:
          mode: 0644
      - src: ./completions/bab.bash
        dst: /usr/share/bash-completion/completions/bab
        file_info:
          mode: 0644
      - src: ./completions/bab.zsh
        dst: /usr/share/zsh/vendor-completions/_bab
        file_info:
          mode: 0644
      - src: ./completions/bab.fish
        dst: /usr/share/fish/vendor_completions.d/bab.fish
        file_info:
          mode: 0644

    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"

    overrides:
      deb:
        provides:
          - bab
        conflicts:
          - bab-bin
        replaces:
          - bab-bin
      rpm:
        provides:
          - bab
        conflicts:
          - bab-bin
        replaces:
          - bab-bin
      apk:
        provides:
          - bab
        conflicts:
          - bab-bin
        replaces:
          - bab-bin

brews:
  - name: bab
    repository:
      owner: bab-sh
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: "[email protected]"
    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"
    homepage: "https://github.com/bab-sh/bab"
    description: "A Simple Task Runner"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "bab"
      bash_completion.install "completions/bab.bash" => "bab"
      zsh_completion.install "completions/bab.zsh" => "_bab"
      fish_completion.install "completions/bab.fish"
    test: |
      system "#{bin}/bab", "--version"

homebrew_casks:
  - name: bab
    repository:
      owner: bab-sh
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: "[email protected]"
    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"
    homepage: "https://github.com/bab-sh/bab"
    description: "A Simple Task Runner"
    license: "MIT"
    directory: Casks
    url:
      verified: github.com/bab-sh/bab
    binary: bab
    completions:
      bash: completions/bab.bash
      zsh: completions/bab.zsh
      fish: completions/bab.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
          end

  - name: "bab@{{ .Major }}.{{ .Minor }}"
    repository:
      owner: bab-sh
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: "[email protected]"
    commit_msg_template: "chore: add {{ .ProjectName }}@{{ .Major }}.{{ .Minor }} ({{ .Tag }})"
    homepage: "https://github.com/bab-sh/bab"
    description: "A Simple Task Runner (version {{ .Major }}.{{ .Minor }}.x)"
    license: "MIT"
    directory: Casks
    url:
      verified: github.com/bab-sh/bab
    binary: bab
    completions:
      bash: completions/bab.bash
      zsh: completions/bab.zsh
      fish: completions/bab.fish
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
          end

scoops:
  - name: bab
    repository:
      owner: bab-sh
      name: scoop-bucket
      branch: main
      token: "{{ .Env.PAT_TOKEN }}"

    commit_author:
      name: goreleaserbot
      email: "[email protected]"

    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"

    homepage: "https://github.com/bab-sh/bab"
    description: "A Simple Task Runner"
    license: MIT

    shortcuts:
      - ["bab.exe", "Bab CLI"]
#winget:
#  - name: bab
#    publisher: bab-sh
#    short_description: "A Simple Task Runner"
#    license: "MIT"
#    homepage: "https://github.com/bab-sh/bab"
#
#    package_identifier: bab-sh.bab
#
#    tags:
#      - cli
#      - task-runner
#      - productivity
#      - developer-tools
#
#    repository:
#      owner: bab-sh
#      name: winget-pkgs-fork
#      branch: "bab-{{ .Version }}"
#      token: "{{ .Env.PAT_TOKEN }}"
#
#      pull_request:
#        enabled: true
#        draft: false
#        base:
#          owner: microsoft
#          name: winget-pkgs
#          branch: master
#
#    release_notes: "{{ .Changelog }}"
#    release_notes_url: "https://github.com/bab-sh/bab/releases/tag/{{ .Tag }}"
#
#    skip_upload: auto

chocolateys:
  - name: bab

    owners: bab-sh
    icon_url: https://avatars.githubusercontent.com/u/191529825
    title: Bab - A Simple Task Runner
    authors: Sebastian Stepper
    project_url: https://bab.sh
    copyright: 2025 bab-sh
    license_url: https://github.com/bab-sh/bab/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/bab-sh/bab
    docs_url: https://github.com/bab-sh/bab#readme
    bug_tracker_url: https://github.com/bab-sh/bab/issues

    tags: "cli task-runner productivity developer-tools automation build-tool"

    summary: A simple and efficient task runner for developers
    description: |
      Bab is a simple and efficient task runner for developers, in other words project commands defined in yaml.
      It helps automate repetitive tasks, manage build processes, and streamline your development workflow.
      Perfect for CLI automation and developer productivity.

    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"

    source_repo: "https://push.chocolatey.org/"

    skip_publish: false

    release_notes: "https://github.com/bab-sh/bab/releases/tag/{{ .Tag }}"

    ids:
      - default

snapcrafts:
  - name: bab-sh

    summary: A simple task runner

    description: A Simple Task Runner

    publish: true
    grade: stable
    confinement: strict
    base: core22

    license: MIT

    apps:
      bab:
        command: bab
        plugs:
          - home
          - network
          - network-bind
          - removable-media

    channel_templates:
      - edge
      - beta
      - candidate
      - stable

aurs:
  - name: bab-bin
    homepage: "https://github.com/bab-sh/bab"
    description: "A Simple Task Runner"
    maintainers:
      - "Sebastian Stepper <sebastian-stepper@gmx.de>"
    license: "MIT"
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/bab-bin.git"

    commit_author:
      name: goreleaserbot
      email: "[email protected]"

    commit_msg_template: "upgpkg: {{ .ProjectName }} {{ .Tag }}"

    package: |-
      # Binary
      install -Dm755 "./bab" "${pkgdir}/usr/bin/bab"

      # Documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/${pkgname}/README.md"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

      # Shell completions
      install -Dm644 "./completions/bab.bash" "${pkgdir}/usr/share/bash-completion/completions/bab"
      install -Dm644 "./completions/bab.zsh" "${pkgdir}/usr/share/zsh/site-functions/_bab"
      install -Dm644 "./completions/bab.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/bab.fish"

aur_sources:
  - name: bab
    homepage: "https://github.com/bab-sh/bab"
    description: "A Simple Task Runner"
    maintainers:
      - "Sebastian Stepper <sebastian-stepper@gmx.de>"
    license: "MIT"
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/bab.git"

    commit_author:
      name: goreleaserbot
      email: "[email protected]"
    commit_msg_template: "upgpkg: {{ .ProjectName }} {{ .Tag }}"
    url_template: "https://github.com/bab-sh/bab/archive/refs/tags/{{ .Tag }}.tar.gz"
    provides:
      - bab
    conflicts:
      - bab-bin
    depends:
      - glibc
    makedepends:
      - go
      - git
    build: |-
      cd "${pkgname}-${pkgver}"
      export CGO_ENABLED=0
      export CGO_CPPFLAGS="${CPPFLAGS}"
      export CGO_CFLAGS="${CFLAGS}"
      export CGO_CXXFLAGS="${CXXFLAGS}"
      export CGO_LDFLAGS="${LDFLAGS}"
      export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"

      go build \
        -ldflags="-s -w -buildid='' -linkmode=external \
          -X github.com/bab-sh/bab/internal/version.Version=${pkgver} \
          -X github.com/bab-sh/bab/internal/version.Commit={{ .Commit }} \
          -X github.com/bab-sh/bab/internal/version.Date={{ .Date }} \
          -X github.com/bab-sh/bab/internal/version.BuiltBy=aur" \
        -o bab .

      # Generate shell completions
      mkdir -p completions
      ./bab completion bash > completions/bab.bash
      ./bab completion zsh > completions/bab.zsh
      ./bab completion fish > completions/bab.fish

    package: |-
      cd "${pkgname}-${pkgver}"
      
      # Binary
      install -Dm755 ./bab "${pkgdir}/usr/bin/bab"
      
      # Documentation
      install -Dm644 ./README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"
      install -Dm644 ./LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"

      # Shell completions
      install -Dm644 ./completions/bab.bash "${pkgdir}/usr/share/bash-completion/completions/bab"
      install -Dm644 ./completions/bab.zsh "${pkgdir}/usr/share/zsh/site-functions/_bab"
      install -Dm644 ./completions/bab.fish "${pkgdir}/usr/share/fish/vendor_completions.d/bab.fish"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

announce:
  discord:
    enabled: true
    message_template: |
      🚀 **{{ .ProjectName }} {{ .Tag }}** is now available!
      
      📋 **Changelog**: {{ .ReleaseURL }}
    author: "Bab Releases"
    color: "3447003"
    icon_url: "https://avatars.githubusercontent.com/u/191529825"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"