version: 2

project_name: bab

builds:
  - id: default
    binary: bab
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/bab-sh/bab/pkg/version.Version={{.Version}}
      - -X github.com/bab-sh/bab/pkg/version.Commit={{.Commit}}
      - -X github.com/bab-sh/bab/pkg/version.Date={{.Date}}
      - -X github.com/bab-sh/bab/pkg/version.BuiltBy=goreleaser
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

homebrew_casks:
  - name: bab
    repository:
      owner: bab-sh
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: "[email protected]"
    commit_msg_template: "chore: update {{ .ProjectName }} to {{ .Tag }}"
    homepage: "https://github.com/bab-sh/bab"
    description: "Bab CLI - A simple task runner"
    license: "MIT"
    directory: Casks
    url:
      verified: github.com/bab-sh/bab
    binary: bab
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
          end
  - name: "bab@{{ .Major }}.{{ .Minor }}"
    repository:
      owner: bab-sh
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: "[email protected]"
    commit_msg_template: "chore: add {{ .ProjectName }}@{{ .Major }}.{{ .Minor }} ({{ .Tag }})"
    homepage: "https://github.com/bab-sh/bab"
    description: "Bab CLI - A simple task runner (version {{ .Major }}.{{ .Minor }}.x)"
    license: "MIT"
    directory: Casks
    url:
      verified: github.com/bab-sh/bab
    binary: bab
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bab"]
          end

release:
  github:
    owner: bab-sh
    name: bab
  mode: append
  skip_upload: false
  make_latest: false