services:
  bab-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bab-docs
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - bab-network
    labels:
      - "com.docker.compose.project=bab-docs"
      - "description=Bab documentation site powered by VitePress"
    tmpfs:
      - /tmp
      - /var/run
      - /var/cache/nginx

networks:
  bab-network:
    driver: bridge
